version: 2
registries:
  python-index-freshbooks-jfrog-io-freshbooks-api-pypi-pypi-simple:
    type: python-index
    url: https://freshbooks.jfrog.io/freshbooks/api/pypi/pypi/simple
    replaces-base: true
    username: "${{secrets.PYTHON_INDEX_FRESHBOOKS_JFROG_IO_FRESHBOOKS_API_PYPI_PYPI_SIMPLE_USERNAME}}"
    password: "${{secrets.PYTHON_INDEX_FRESHBOOKS_JFROG_IO_FRESHBOOKS_API_PYPI_PYPI_SIMPLE_PASSWORD}}"

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 99
  registries:
  - python-index-freshbooks-jfrog-io-freshbooks-api-pypi-pypi-simple
