language: python

dist: 'trusty'

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

matrix:
  include:
    - python: "2.7"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"

before_install:
  - sudo apt-get -qq update

install:
  - pip install -r requirements-dev.txt
  - pip install .

script:
  - nosetests

notifications:
  email: false

deploy:
  provider: pypi
  user: freshbooks
  password:
    secure: iQ7ZvO8KxJEjCeCXj962n4LuYFy4XCtnJ2GSmsMtKfFmDEUQtz/U1WfxxCddIO2nuQyoxemziVEF++bzzpxpul7gioyuOzVIKL3nRIsWtOvwwCO9Pp+qy8pCdqrQd8Wim0vUcmyoAU90jvSjCfR1RwMA8Nc6ar7ilIM5JdFDIMM=
  on:
    tags: true
